name: Lint and Test Charts

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --charts challenge-2
      
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Run chart-testing (install)
        run: ct install --charts challenge-2

      - name: Validate values.yaml schema
        run: helm lint -f challenge-2/values.yaml ./challenge-2